CREATE TYPE OP_TYPE AS ENUM('insert', 'update', 'delete');

CREATE TABLE SYSLOG (
	ID	    SERIAL       PRIMARY KEY,
	SERVICE	    VARCHAR      NOT NULL,
	REQUESTOR   VARCHAR      NOT NULL,
	ENTITY      VARCHAR      NOT NULL,
	OPERATION   OP_TYPE      NOT NULL,
	DATETIME    TIMESTAMPTZ  NOT NULL,
	DESCRIPTION VARCHAR
)

