CREATE TABLE SYSLOG (
	ID	    SERIAL       PRIMARY KEY,
	SERVICE	    VARCHAR      NOT NULL,
	REQUESTOR   VARCHAR      NOT NULL,
	ENTITY      VARCHAR      NOT NULL,
	OPERATION   SMALLINT     NOT NULL, -- Inserção, Atualização, Remoção
	DATETIME    TIMESTAMPTZ  NOT NULL,
	DESCRIPTION VARCHAR
)

