CREATE TABLE SYSLOG (
	ID	    SERIAL       PRIMARY KEY,
	SERVICE	    VARCHAR      NOT NULL,
	"USER"	    VARCHAR      NOT NULL,
	OPERATION   SMALLINT     NOT NULL, -- Inserção, atualização, remoção
	DATETIME    TIMESTAMPTZ  NOT NULL,
	DESCRIPTION VARCHAR
)

