[package]
name = "minerva-rpc"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
tonic = "0.7"
tokio-stream = {version = "0.1", features = ["net"]}
prost = "0.10"
dotenv = "0.15.0"

[build-dependencies]
tonic-build = "0.7"
