[package]
name = "minerva-cache"
version = "0.0.0"
edition = "2021"
description = "Cache library for the Minerva System"
authors = ["Lucas S. Vieira <lucasvieira@protonmail.com>"]

[lib]
path = "src/lib.rs"

[dependencies]
