[workspace]
members = [
        "minerva-rpc",
        "minerva-data",
        "minerva-cache",
        "minerva-broker",
        "minerva-user",
        "minerva-session",
        "minerva-rest",
        "minerva-runonce",
        "minerva-dispatch",
]

