[workspace]
members = [
	"minerva-rpc",
	"minerva-data",
	"minerva-cache",
        "minerva-broker",
	"minerva-user",
	"minerva-session",
	"minerva-product",
	"minerva-stock",
	"minerva-rest",
	"minerva-runonce",
        "minerva-report",
        "minerva-dispatch",
]

