version: "3"

services:
  # Front-End service
  frontend:
    image: luksamuk/minerva_frontend:0.1.1
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - "rest"
    networks:
      - minerva_system
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  
  # REST service
  rest:
    image: luksamuk/minerva_rest:0.2.2
    environment:
      - USER_SERVICE_SERVER=user
      - SESSION_SERVICE_SERVER=session
    ports:
      - 9000:9000
    depends_on:
      - "user"
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP = REST_SERVICE]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  
  # RUNONCE service
  runonce:
    image: luksamuk/minerva_runonce:0.2.1
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    depends_on:
      - "postgresql"
      - "mongodb"
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP = RUNONCE_SERVICE]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  
  # USER service
  user:
    image: luksamuk/minerva_user:0.2.2
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP = USER_SERVICE]
      restart_policy:
        condition: on-failure

  # SESSION service
  session:
    image: luksamuk/minerva_session:0.1.1
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP = SESSION_SERVICE]
      restart_policy:
        condition: on-failure

  # PostgreSQL 14
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # pgAdmin 4
  pgadmin:
    image: luksamuk/minerva_pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8484:80"
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # MongoDB 5
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:5
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb-data:/data/db
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # Visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
        
networks:
  minerva_system:

volumes:
  db-data:
  mongodb-data:

