version: "3"

services:
  # Front-End service
  frontend:
    image: luksamuk/minerva_frontend:latest
    environment:
      - NGINX_PORT=80
    ports:
      - "80:80"
    depends_on:
      - "rest"
  
  # REST service
  rest:
    image: luksamuk/minerva_rest:0.2.0
    environment:
      - USER_SERVICE_SERVER=users
      - SESSION_SERVICE_SERVER=session
    ports:
      - "9000:9000"
    depends_on:
      - "users"
  
  # RUNONCE service
  runonce:
    image: luksamuk/minerva_runonce:0.2.0
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    depends_on:
      - "postgresql"
      - "mongodb"
  
  # USERS service
  users:
    image: luksamuk/minerva_users:0.2.0
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
    depends_on:
      runonce:
        condition: service_completed_successfully

  # SESSION service
  session:
    image: luksamuk/minerva_session:0.1.0
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    depends_on:
      runonce:
        condition: service_completed_successfully

  # PostgreSQL 14
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
    volumes:
      - ../minerva-postgresql:/var/lib/postgresql/data

  # pgAdmin 4
  pgadmin:
    image: luksamuk/minerva_pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8484:80"

  # MongoDB 5
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:5
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ../minerva-mongodb:/data/db


