version: "3"

services:
  # Front-End service
  frontend:
    image: luksamuk/minerva_frontend:latest
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - "rest"
    networks:
      - minerva_system
    deploy:
      restart_policy:
        condition: on-failure
  
  # REST service
  rest:
    image: luksamuk/minerva_rest:latest
    environment:
      - USER_SERVICE_SERVER=user
      - SESSION_SERVICE_SERVER=session
    ports:
      - 9000:9000
    depends_on:
      - "user"
    networks:
      - minerva_system
    deploy:
      restart_policy:
        condition: on-failure
  
  # RUNONCE service
  runonce:
    image: luksamuk/minerva_runonce:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    depends_on:
      - "postgresql"
      - "mongodb"
    networks:
      - minerva_system
    deploy:
      restart_policy:
        condition: on-failure
  
  # USER service
  user:
    image: luksamuk/minerva_user:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
    networks:
      - minerva_system
    deploy:
      restart_policy:
        condition: on-failure

  # SESSION service
  session:
    image: luksamuk/minerva_session:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    networks:
      - minerva_system
    deploy:
      restart_policy:
        condition: on-failure

  # PostgreSQL 14
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minerva_system

  # pgAdmin 4
  pgadmin:
    image: luksamuk/minerva_pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8484:80"
    networks:
      - minerva_system

  # MongoDB 5
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:5
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb-data:/data/db
    networks:
      - minerva_system

networks:
  minerva_system:

volumes:
  db-data:
  mongodb-data:

