version: "3"

services:
  # Front-End service
  frontend:
    image: minerva_frontend
    environment:
      - NGINX_PORT=80
    build:
      dockerfile: build/Dockerfile.FRONTEND
      context: .
    ports:
      - "80:80"
    depends_on:
      - "rest"
  
  # REST service
  rest:
    image: minerva_rest
    environment:
      - USER_SERVICE_SERVER=users
      - SESSION_SERVICE_SERVER=session
    build:
      dockerfile: build/Dockerfile.REST
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - "users"
  
  # RUNONCE service
  runonce:
    image: minerva_runonce
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    build:
      dockerfile: build/Dockerfile.RUNONCE
      context: .
    depends_on:
      - "postgresql"
      - "mongodb"
  
  # USERS service
  users:
    image: minerva_users
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
    build:
      dockerfile: build/Dockerfile.USER
      context: .
    depends_on:
      runonce:
        condition: service_completed_successfully

  # SESSION service
  session:
    image: minerva_session
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    build:
      dockerfile: build/Dockerfile.SESSION
      context: .
    depends_on:
      runonce:
        condition: service_completed_successfully

  # PostgreSQL
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
    volumes:
      - ../minerva-postgresql:/var/lib/postgresql/data

  # pgAdmin 4
  pgadmin:
    image: minerva_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - GUNICORN_ACCESS_LOGFILE=/dev/null
    build:
      dockerfile: Dockerfile.PGADMIN
      context: build
    ports:
      - "8484:80"

  # MongoDB
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:5
    volumes:
      - ../minerva-mongodb:/data/db

