CREATE TABLE STOCK_MOV (
	ID	      SERIAL	     PRIMARY KEY,
	PRODUCT_ID    SERIAL	     NOT NULL,
	DOCUMENT      VARCHAR	     NOT NULL,
	AMOUNT	      NUMERIC(12,3)  NOT NULL,
	COST          NUMERIC(13,4)  NOT NULL      DEFAULT 0.0000, -- Preço de custo
	SHIPPING_COST NUMERIC(13,4)  NOT NULL      DEFAULT 0.0000, -- Preço de frete
	DATE          TIMESTAMPTZ    NOT NULL,

	CONSTRAINT FK_PRODUCT
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
)

