apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker-rabbitmqcluster
  namespace: minerva
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user = rabbitmq
                  default_pass = minerva
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer
