apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-deployment
spec:
  template:
    metadata:
      name: dispatch
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch-container
          image: luksamuk/minerva_dispatch:0.1.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ports-configmap
            - configMapRef:
                name: servers-configmap
          resources:
            requests:
              cpu: 10m
  replicas: 3
  selector:
    matchLabels:
      app: dispatch
