apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 31087
  selector:
    app: grafana
  sessionAffinity: None
