apiVersion: v1
kind: ConfigMap
metadata:
  name: log-configmap
  namespace: minerva
data:
  logging.yml: |
    refresh_rate: 30 seconds
    appenders:
      stdout:
        kind: console
        encoder:
          pattern: "{h({l})} {m} [{f}:{L}]{n}"
    root:
      level: info
      appenders:
        - stdout

