---
# Minerva System -- USER: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: minerva
spec:
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: luksamuk/minerva_user:0.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9010
          envFrom:
            - configMapRef:
                name: ports-configmap
            - configMapRef:
                name: servers-configmap
          resources:
            requests:
              cpu: 10m
  replicas: 2
  selector:
    matchLabels:
      app: user
---
# Minerva System -- USER: Service
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: minerva
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 9010
---
# Minerva System -- USER: Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: minerva
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
