apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongoexpress-secret
data:
  ME_CONFIG_MONGODB_AUTH_USERNAME: cm9vdA==
  ME_CONFIG_MONGODB_AUTH_PASSWORD: bW9uZ28=
  ME_CONFIG_BASICAUTH_USERNAME: bW9uZ28=
  ME_CONFIG_BASICAUTH_PASSWORD: bW9uZ28=
