apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
data:
  servers.json: |
    {
        "Servers": {
            "1": {
                "Name": "PostgreSQL",
                "Group": "Servers",
                "Host": "postgresql-svc",
                "Port": 5432,
                "MaintenanceDB": "postgres",
                "Username": "postgres",
                "SSLMode": "prefer",
                "PassFile": "/pgpassfile"
            }
        }
    }
