apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['broker-rabbitmqcluster:15692']
