apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  serviceName: redis-svc
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: redis-cluster-config
          image: redis:7-alpine
          command: ["sh", "-c"]
          args:
            - |
              cp /tmp/redis/redis.conf /etc/redis/redis.conf
              
              echo "Tentando acessar Redis Sentinel..."
              MASTER_FDQN=`hostname  -f | sed -e 's/redis-[0-9]\./redis-0./'`
              if [ "$(redis-cli -h sentinel -p 5000 ping)" != "PONG" ]; then
                  echo "Servidor Redis master não encontrado via Sentinel, usando redis-0 por padrão"

                  if [ "$(hostname)" == "redis-0" ]; then
                      echo "Esta é a réplica redis-0, a configuração não será atualizada."
                  else
                      echo "Atualizando arquivo redis.conf..."
                      echo "slaveof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
                  fi
              else
                  echo "Redis Sentinel encontrado. Procurando master..."
                  MASTER="$(redis-cli -h sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
                  echo "Master encontrado: $MASTER, atualizando arquivo redis.conf..."
                  echo "slaveof $MASTER 6379" >> /etc/redis/redis.conf
              fi
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/
            - name: redis-initial-config
              mountPath: /tmp/redis/
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server"]
          args: ["/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/
          resources:
            requests:
              memory: 50Mi
              cpu: 15m
            limits:
              memory: 100Mi
              cpu: 20m
      volumes:
        - name: redis-config
          emptyDir: {}
        - name: redis-initial-config
          configMap:
            name: redis-configmap
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc

