version: "3"

services:
  # Front-End service
  frontend:
    image: luksamuk/minerva_frontend:latest
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - "rest"
    networks:
      - minerva_system
    restart: on-failure:5
  
  # REST service
  rest:
    image: luksamuk/minerva_rest:latest
    environment:
      - USER_SERVICE_SERVER=user
      - SESSION_SERVICE_SERVER=session
    ports:
      - 9000:9000
    depends_on:
      - "user"
    networks:
      - minerva_system
    restart: on-failure:5
  
  # RUNONCE service
  runonce:
    image: luksamuk/minerva_runonce:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - RABBITMQ_SERVICE_SERVER=rabbitmq
    depends_on:
      - "postgresql"
      - "mongodb"
      - "rabbitmq"
    networks:
      - minerva_system
    restart: on-failure:5
  
  # USER service
  user:
    image: luksamuk/minerva_user:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - RABBITMQ_SERVICE_SERVER=rabbitmq
    networks:
      - minerva_system
    restart: on-failure:5

  # SESSION service
  session:
    image: luksamuk/minerva_session:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - REDIS_SERVICE_SERVER=redis
      - RABBITMQ_SERVICE_SERVER=rabbitmq
    networks:
      - minerva_system
    restart: on-failure:5

  # DISPATCH service
  dispatch:
    image: luksamuk/minerva_dispatch:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - REDIS_SERVICE_SERVER=redis
      - RABBITMQ_SERVICE_SERVER=rabbitmq
      - SESSION_SERVICE_SERVER=session
      - SESSION_SERVICE_PORT=9011
    depends_on:
      - "rabbitmq"
    networks:
      - minerva_system
    restart: on-failure:5

  # PostgreSQL 14
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minerva_system
    restart: on-failure:5

  # MongoDB 4
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:4
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - minerva_system
    restart: on-failure:5

  # Redis 7
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - minerva_system
    restart: on-failure:5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=minerva
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - minerva_system
    restart: on-failure:5
    
networks:
  minerva_system:

volumes:
  db-data:
  mongodb-data:
  redis-data:

