version: "3"

services:
  # REST service
  rest:
    image: luksamuk/minerva_rest:latest
    environment:
      - USER_SERVICE_SERVER=user
      - SESSION_SERVICE_SERVER=session
      - LOG_CONFIG_FILE=/cfg/logging.yml
    volumes:
      - ../logging.yml:/cfg/logging.yml
    ports:
      - 9000:9000
    network_mode: "host"
    restart: on-failure:5
  
  # RUNONCE service
  # runonce:
  #   image: luksamuk/minerva_runonce:latest
  #   environment:
  #     - DATABASE_SERVICE_SERVER=localhost
  #     - MONGO_SERVICE_SERVER=localhost
  #     - RABBITMQ_SERVICE_SERVER=rabbitmq
  #   depends_on:
  #     - "postgresql"
  #     - "mongodb"
  #     - "rabbitmq"
  #   restart: on-failure:5
  
  # USER service
  user:
    image: luksamuk/minerva_user:latest
    environment:
      - DATABASE_SERVICE_SERVER=localhost
      - RABBITMQ_SERVICE_SERVER=localhost
      - LOG_CONFIG_FILE=/cfg/logging.yml
    user: appuser
    volumes:
      - ../logging.yml:/cfg/logging.yml
    network_mode: "host"
    restart: on-failure:5

  # SESSION service
  session:
    image: luksamuk/minerva_session:latest
    environment:
      - DATABASE_SERVICE_SERVER=localhost
      - MONGO_SERVICE_SERVER=localhost
      - REDIS_SERVICE_SERVER=localhost
      - RABBITMQ_SERVICE_SERVER=rabbitmq
      - LOG_CONFIG_FILE=/cfg/logging.yml
    user: appuser
    volumes:
      - ../logging.yml:/cfg/logging.yml
    network_mode: "host"
    restart: on-failure:5

  # DISPATCH service
  dispatch:
    image: luksamuk/minerva_dispatch:latest
    environment:
      - DATABASE_SERVICE_SERVER=localhost
      - MONGO_SERVICE_SERVER=localhost
      - REDIS_SERVICE_SERVER=localhost
      - RABBITMQ_SERVICE_SERVER=localhost
      - SESSION_SERVICE_SERVER=session
      - SESSION_SERVICE_PORT=9011
    user: appuser
    network_mode: "host"
    restart: on-failure:5


