version: "3"

services:
  # Front-End service
  frontend:
    image: luksamuk/minerva_frontend:latest
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - "rest"
    networks:
      - minerva_system
    restart: on-failure:5
  
  # REST service
  rest:
    image: luksamuk/minerva_rest:latest
    environment:
      - USER_SERVICE_SERVER=user
      - SESSION_SERVICE_SERVER=session
    ports:
      - 9000:9000
    depends_on:
      - "user"
    networks:
      - minerva_system
    restart: on-failure:5
  
  # RUNONCE service
  runonce:
    image: luksamuk/minerva_runonce:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
    depends_on:
      - "postgresql"
      - "mongodb"
    networks:
      - minerva_system
    restart: on-failure:5
  
  # USER service
  user:
    image: luksamuk/minerva_user:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
    networks:
      - minerva_system
    restart: on-failure:5

  # SESSION service
  session:
    image: luksamuk/minerva_session:latest
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - REDIS_SERVICE_SERVER=redis
    networks:
      - minerva_system
    restart: on-failure:5

  # PostgreSQL 14
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minerva_system
    restart: on-failure:5

  # pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8484:80"
    volumes:
      - ${PWD}/swarm/servers.json:/pgadmin4/servers.json
    networks:
      - minerva_system
    restart: on-failure:5

  # MongoDB 5
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:5
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb-data:/data/db
    networks:
      - minerva_system
    restart: on-failure:5

  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
    ports:
      - "8686:8081"
    networks:
      - minerva_system
    restart: on-failure:5

  # Redis 7
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - minerva_system
    restart: on-failure:5

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8787:8081"
    networks:
      - minerva_system
    restart: on-failure:5

networks:
  minerva_system:

volumes:
  db-data:
  mongodb-data:
  redis-data:

