apiVersion: batch/v1
kind: Job
metadata:
  name: runonce-job
spec:
  template:
    metadata:
      name: runonce
      labels:
        app: runonce
    spec:
      containers:
        - name: runonce
          image: luksamuk/minerva_runonce:0.2.0
          envFrom:
            - configMapRef:
                name: runonce-configmap
      restartPolicy: OnFailure
  backoffLimit: 10
  ttlSecondsAfterFinished: 3000
