version: "3"

services:
  # Front-End service
  frontend:
    image: luksamuk/minerva_frontend:0.1.1
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - "rest"
    networks:
      - minerva_system
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  
  # REST service
  rest:
    image: luksamuk/minerva_rest:0.2.2
    environment:
      - USER_SERVICE_SERVER=user
      - SESSION_SERVICE_SERVER=session
    ports:
      - 9000:9000
    depends_on:
      - "user"
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP = REST_SERVICE]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  
  # RUNONCE service
  runonce:
    image: luksamuk/minerva_runonce:0.3.0
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - RABBITMQ_SERVICE_SERVER=rabbitmq
    depends_on:
      - "postgresql"
      - "mongodb"
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP = RUNONCE_SERVICE]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  
  # USER service
  user:
    image: luksamuk/minerva_user:0.3.0
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - RABBITMQ_SERVICE_SERVER=rabbitmq
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP = USER_SERVICE]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  # SESSION service
  session:
    image: luksamuk/minerva_session:0.1.2
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - REDIS_SERVICE_SERVER=redis
      - RABBITMQ_SERVICE_SERVER=rabbitmq
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP = SESSION_SERVICE]
      restart_policy:
        condition: on-failure

  # DISPATCH service
  dispatch:
    image: luksamuk/minerva_dispatch:0.1.0
    environment:
      - DATABASE_SERVICE_SERVER=postgresql
      - MONGO_SERVICE_SERVER=mongodb
      - REDIS_SERVICE_SERVER=redis
      - RABBITMQ_SERVICE_SERVER=rabbitmq
      - SESSION_SERVICE_SERVER=session
      - SESSION_SERVICE_PORT=9011
    networks:
      - minerva_system
    deploy:
      mode: replicated
      replicas: 3
      labels: [APP = DISPATCH_SERVICE]
      restart_policy:
        condition: on-failure

  # PostgreSQL 14
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8484:80"
    volumes:
      - /vagrant/servers.json:/pgadmin4/servers.json
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # MongoDB 5
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:5
    volumes:
      - mongodb-data:/data/db
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
    ports:
      - "8686:8081"
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]
        
  # Visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8585:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  # Redis 7
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - minerva_system
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8787:8081"
    networks:
      - minerva_system
    deploy:
      placement:
        constraints: [node.role == manager]

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=minerva
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - minerva_system
    deploy:
      restart-policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
        
        
networks:
  minerva_system:

volumes:
  db-data:
  mongodb-data:
  redis-data:

