name: minerva_frontend
description: Minerva System Front-End
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  validatorless: ^1.2.1
  intl: ^0.17.0
  flutter_neumorphic: ^3.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
