[book]
authors = ["Lucas S. Vieira"]
language = "pt-br"
multilingual = false
src = "src"
title = "Minerva System"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[preprocessor.plantuml]
plantuml-cmd="plantuml"
clickable-img=true

