refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{t}] {h({l})} {m}{n}"

  logfile:
    kind: rolling_file
    path: "./log/dispatch-0.log"
    append: true
    encoder:
      pattern: "{d(%+)(utc)} [{t}] {h({l})} {M}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: ./log/dispatch-{}.log
        count: 2
        base: 1

root:
  level: debug
  appenders:
    - stdout
    - logfile

