name: Deploy documentation

on:
  push:
    branches: [master]
    
jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: fedora:37
    steps:
      - name: Adjust locale
        continue-on-error: true
        run: |
          dnf install -y langpacks-pt_BR glibc-locale-source
          localedef --verbose --force -i pt_BR -f UTF-8 pt_BR.UTF-8
          export LANG=pt_BR.UTF-8
          echo "LANG=pt_BR.UTF-8" >> $GITHUB_ENV
      
      - name: Install Graphviz, PlantUML and other tools
        run: |
          dnf install -y curl dnf-plugins-core openssl \
          openssl-devel cmake gcc clang make git unzip \
          libpq libpq-devel rsync graphviz plantuml \
          protobuf-devel protobuf-compiler
        
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          toolchain: 1.65.0
          profile: minimal

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: "3.0.1"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust build cache
        uses: Swatinem/rust-cache@v2

      - name: Install mdBook
        run: |
          cargo install mdbook
          cargo install mdbook-graphviz
          cargo install mdbook-plantuml

      - name: Generate Rust documentation
        run: |
         cargo doc --no-deps --document-private-items
         mv target/doc docs/src/doc
         rm docs/src/.gitignore

      - name: Generate Dart documentation
        run: |
          cd minerva_frontend
          flutter pub get
          dart doc .
          cd ..
          mv minerva_frontend/doc/api docs/src/doc/minerva_frontend
         
      - name: Generate book
        run: |
          cd docs
          mdbook build
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/book

